Repository wecode-bootcamp-korea/42-2nd-OneOhOne-backend, pull requests merged in 2023-03, with the labels that each got.

#4 [ADD] 강의 전체/카테고리별 리스트 조회 기능구현
  .gitignore
  __tests__/lectures.test.js
  app.js
  controllers/lectureController.js
  models/index.js
  models/lectureDao.js
  package-lock.json
  package.json
  routes/index.js
  routes/lectureRouter.js
  server.js
  services/lectureService.js
Labels: 완료

#7 [ADD] 강의 상세페이지 API 기능 구현
  controllers/lectureController.js
  models/lectureDao.js
  routes/lectureRouter.js
  services/lectureService.js
Labels: 완료

#6 [ADD] signup/in 기능 구현
  .gitignore
  __tests__/user.test.js
  controllers/userController.js
  middlewares/auth.js
  models/userDao.js
  routes/index.js
  routes/userRouter.js
  services/userService.js
  utils/validators.js
Labels: 완료

#12 [42기 최원경] fix database tables/column 수정
  db/migrations/20230227080613_categories.sql
  db/migrations/20230227080623_lectures_status.sql
  db/migrations/20230227080635_creators.sql
  db/migrations/20230227083950_lectures.sql
  db/migrations/20230227092246_detail_images.sql
  db/migrations/20230227092700_curriculums.sql
  db/migrations/20230227093152_videos.sql
Labels: 멘토 리뷰 요청, 완료

#10 Feature/mediaplayer [ADD] GET contents 비디오 조회
  controllers/videoController.js
  models/videoDao.js
  routes/index.js
  routes/videoRouter.js
  services/videoService.js
Labels: 멘토 리뷰 요청

#14 fix lecture db 테이블및 colums 변경으로 인한 쿼리문 수정
  models/lectureDao.js
Labels: 멘토 리뷰 요청

#13 fix kakaosignin/ 카카오로그인 데이터베이스에 안들어오는 정보 수정
  models/userDao.js
  services/userService.js
  services/videoService.js
Labels: 멘토 리뷰 요청

#16 [Fix] Fix/database migration 수정작업
  db/db/migrations/20230309192016_creators.sql
  db/db/migrations/20230309192043_payment_types.sql
  db/db/migrations/20230309192056_users.sql
  db/db/migrations/20230309192107_lectures.sql
  db/db/migrations/20230309192118_reviews.sql
  db/db/migrations/20230309192134_detail_images.sql
  db/db/migrations/20230309192148_curriculums.sql
  db/db/migrations/20230309192156_videos.sql
  db/db/migrations/20230309192201_carts.sql
  db/db/migrations/20230309192207_orders.sql
  db/db/migrations/20230309192217_order_items.sql
  db/migrations/20230309075950_modify_users_table.sql
  db/migrations/20230309080604_modify_detail_images_table.sql
  db/migrations/20230309080619_modify_curriculums_table.sql
  db/migrations/20230309080648_modify_videos_table.sql
  db/migrations/20230309080659_modify_lectures_table.sql
Labels: 멘토 리뷰 요청
